version: '3.6'
services:
  sasskit-img-manager:
    container_name: sasskit-img-manager
    restart: always
    build: 
     context: image-service
     dockerfile: Dockerfile
    ports:
     - 3210:3000
  authentication-service:
    container_name: sass-auth-service
    restart: always
    build:
      context: authentication-service
      dockerfile: Dockerfile
    ports:
     - 3710:3000
  user-action-service:
    container_name: user-action-service
    restart: always
    build:
      context: hasura-user-actions
      dockerfile: Dockerfile
    ports:
      - 4710:3000
  saaskit.postgres:
    container_name: saaskit-pg
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  saaskit.graphql-engine:
    container_name: saaskit-graphql
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8980:8080"
    depends_on:
    - "saaskit.postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@saaskit.postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: PsTmU81#6lKgP0s1T1V3plmMgC
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIC/TCCAeWgAwIBAgIJS7r3+hWwTjMlMA0GCSqGSIb3DQEBCwUAMBwxGjAYBgNV\nBAMTEWRldi1hN2UuYXV0aDAuY29tMB4XDTIwMDQxNDA1MTk0OFoXDTMzMTIyMjA1\nMTk0OFowHDEaMBgGA1UEAxMRZGV2LWE3ZS5hdXRoMC5jb20wggEiMA0GCSqGSIb3\nDQEBAQUAA4IBDwAwggEKAoIBAQDWmrYPzIB4ENJewYoD4DFPkqDKFZEm3I/+25/O\nDN/MEI8Q+nZMuJCLSjKhT6Aci+6njHsNhuZIne+0RFLDopqCOL6kpf4FpxtZ31OA\n8ELjLCQEumU8UVKOUlnz4ATw/PEJMEd0K79iwur6K7AsqCm4HAaSNN9TFqkt3kRA\nb6YLfoGzEH5Scts18xMw4s3chhB9nfM7jrx45/yWGu8447QtaYwL7Sg62ovwKl0t\nIgKqYbPP6ebaJpyG5FUh3F12qxk0T9Fk8mh9qkEtfAttlvFpR16NCqd+SkhkphiS\nJ253Yr1DgZF/Au7jd9X1xY36Mh27DPDcKwvg8sBszke1lJn7AgMBAAGjQjBAMA8G\nA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFEggaBjhQdJqMR1OQwkaJnvqSKjQMA4G\nA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAuAkLlUpEEE0y3i6oFY0o\nr3oXv5ldqnBmUXJUEhEbKj3xT3Whb5Ctx60w53NidLoDCH+j9Ap2Nq5VvVbKKOGp\nnIVMwTbexbGvgJovO5zTBJ9wKYwwtU1yIQW9J7zRcBVaX8afqvFmeCO2MRSWcGyF\ny4MnBM9E3FyVjfksK6iYfEDRP1MJAuYpF0ElOEjMIivBPz+8g7cFw4Au7ZuTh/S8\nISKkhPPNoAV7XwgQrhXrfsqhqxVoxP4xZEKeWrj7r4DiYLHux0nBYxr90LJ0RF5T\nx6aR5LelQ6a8kLbitHAXtTmwDcI6UPboCUik4UuMAsDO+cMlEK04h3j28dD+dAtd\nAw==\n-----END CERTIFICATE-----"}'
volumes:
  db_data:
